import setuptools

setuptools.setup(
    name="wittgenstein",
    version="0.3.5",
    license="MIT",
    description="Ruleset covering algorithms for explainable machine learning",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="Ilan Moscovitz",
    author_email="ilan.moscovitz@gmail.com",
    url="https://github.com/imoscovitz/wittgenstein",
    keywords=[
        "Classification",
        "Decision Rule",
        "Machine Learning",
        "Explainable AI",
        "XAI",
        "Interpretable Machine Learning",
        "Data Science",
        "RIPPER",
        "IREP",
        "Rule Learning",
        "Ruleset",
        "Transparent Machine Learning",
    ],

    packages=setuptools.find_packages(),
    install_requires=["pandas", "numpy"],
    python_requires=">=3.8",
    classifiers=[
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "License :: OSI Approved :: MIT License",
    ],
    include_package_data=True,
    package_data={"": ["data/*.csv"]},
)
